### ISSUE TITLE
`not` in assertions is ignored

### ISSUE THREAD

**Issue by iensu** [astorije/chai-immutable#57]
Given the following assertion:

`expect(fromJS({ x: 1})).to.not.have.key('y');`

I get the following result:

`AssertionError: expected 'Map { "x": 1 }' to have key 'y'`

So it seems that the `not` statement in the assertion is ignored.

I am using:

mocha 2.4.5
chai 3.5.0
chai-immutable: 1.5.4

**Comment by astorije** [comment]
Well that's interesting. Have you noticed this behavior with other assertions of the plugin?

I need to investigate, but if confirmed, I'm surprised the test suite didn't catch this, really.

**Comment by iensu** [comment]
Hi again!

Yes, I had a look at the test suite and it seems it should be covered, so I did some further investigation and it seems that it is https://github.com/prodatakey/dirty-chai that's the culprit here. Turning it off resolves the issue. 

Thanks a lot for your time, I'm going to close this issue.

**Comment by iensu** [comment]
As a side note, I managed to get chai-immutable and dirty-chai working together by loading immutable-chai before loading dirty-chai

**Comment by astorije** [comment]
Hey @iensu, thanks for closing the loop!
That makes sense, there is [similar requirement when using `chai-immutable` along with `chai-as-promised`](https://github.com/astorije/chai-immutable#using-chai-immutable-with-chai-as-promised).

I'm going to update the documentation to reflect that and will ping you so that you can proof-read.
